name: Build & publish to TestPyPI
# on:
#   release:
#     types: [published]
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # latest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Upload packages
        uses: actions/upload-artifact@v3
        with:
          name: Packages
          path: dist
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Download packages
        uses: actions/download-artifact@v3
        with:
          name: Packages
          path: dist
      # https://github.com/pypa/gh-action-pypi-publish/tree/release/v1#trusted-publishing
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.8.7
        with:
            repository-url: https://test.pypi.org/legacy/
