name: Build & publish on TestPyPI
# on:
#   release:
#     types: [published]
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # latest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Upload packages
        uses: actions/upload-artifact@v3
        with:
          name: Packages
          path: dist
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download packages
        uses: actions/download-artifact@v3
        with:
          name: Packages
          path: dist
      - name: List artifacts
        run: |
          ls .
          ls dist
  #     # https://github.com/pypa/gh-action-pypi-publish/tree/release/v1#trusted-publishing
  #     - name: Publish package distributions to TestPyPI
  #       uses: pypa/gh-action-pypi-publish@f5622bde02b04381239da3573277701ceca8f6a0
  #       with:
  #           repository-url: https://test.pypi.org/legacy/

  # publish:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     id-token: write
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.11'
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install build
  #     # https://github.com/pypa/gh-action-pypi-publish/tree/release/v1#trusted-publishing
  #     # TODO: Try to separate building from publishing — this makes sure that any
  #     # scripts maliciously injected into the build or test environment won't
  #     # be able to elevate privileges while flying under the radar.
  #     - name: Build package
  #       run: python -m build
  #     # https://github.com/pypa/gh-action-pypi-publish/tree/release/v1#trusted-publishing
  #     - name: Publish package distributions to TestPyPI
  #       uses: pypa/gh-action-pypi-publish@f5622bde02b04381239da3573277701ceca8f6a0
  #       with:
  #           repository-url: https://test.pypi.org/legacy/
